# Generated by Django 4.1.1 on 2023-02-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210720_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='height',
            new_name='Rank',
        ),
        migrations.RemoveField(
            model_name='data',
            name='age',
        ),
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sex',
        ),
        migrations.AddField(
            model_name='data',
            name='Nationality',
            field=models.PositiveIntegerField(choices=[(0, 'India'), (1, 'Ethiopia'), (2, 'Nepal')], null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Tenth',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Twelth',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
